### ISSUE TITLE
Project Unify slug is "refugee_tech" so pairing events won't be forwarded to proper slack channel

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#937] opened 2016-03-22 20:23 UTC
...

**Comment by freeranger** [comment] 2016-03-22 20:43
This is basically a duplicate of https://github.com/AgileVentures/WebsiteOne/issues/828

**Comment by tansaku** [comment] 2016-03-23 17:29
hard coded a fix in AgileVentures/agile-bot#11

**Closed** 2016-03-23 17:30 UTC
