### ISSUE TITLE
Upgrade to Premium Plus button fails when you click on it

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#1493] opened 2017-01-13 07:36 UTC
Looking at Bryan Yaps profile:
http://www.agileventures.org/users/bryan-yap

When I click on "Upgrade to Premium Plus" I get a:

```
500 Internal Error
Something went terribly wrong

```
I would expect this button to take me to some sort of upgrade page

**Comment by tansaku** [comment] 2017-01-20 19:13
oops - hmm Bryan is already a premium member - in principle upgrading him there would take him to Premium Plus, but charge his card for it .. well it's mixing the sponsorship with the individual's own membership, which is probably why it (sensibly) failed, but don't understand why we don't get an airbrake error there ...

I don't know if our current model is sophisticated enough to represent this - probably in the first instance, folks who are paying their own way shouldn't have a sponsorship upgrade option shown to other users, at least until we've got people wanting to actually do that ...

**Comment by freeranger** [comment] 2017-01-22 18:28
Yes, I clicked on "Upgrade to Premium Plus" so I was expecting a premium plus upgrade option as opposed to an error :)

Charging the individual for the upgrade seems undesirable and potentially rather dangerous - now that this details is available publicly (here), anyone could go in and try to upgrade people and have the members cards charged - assuming the page didn't error of course.

Suggestion:  By default members are not available to be sponsored (whether they are free members or already on some paid tier) - you might take offence that someone things you "need" sponsorship when in fact you are happy with your current membership, so you have to specifically opt to be available to be sponsored.

As a paid member, as an interim measure, only you can upgrade your own membership.
It does sound like you need a more sophisticated payment model to allow people to move between free/paid/sponsored models.

Something to think about: If I am on tier X and someone sponsors me to tier Y, does that person pay the full Y and I no longer pay anything, or do I pay X and the sponsor pays (Y-X)?  And what happens if the sponsor stops - do I drop back to free or to my previous level?

**Comment by tansaku** [comment] 2017-01-24 16:37
duplicate of #1437

**Closed** 2017-02-24 12:40 UTC
Labels: bug, ux-bug
