### ISSUE TITLE
Feature: subscribe to AgileVentures calendar

### ISSUE THREAD

**Issue by ethanstrominger** [AgileVentures/WebsiteOne#3530] opened 2020-04-24 11:58 UTC
## Expected Behavior

Not a bug

**New Feature**
I would like to be able to subscribe to the AgileVentures catalog as I do other calendars that have a public URL.  For instance, I can subscribe to Agile Events in Google Calendar using: https://calendar.google.com/calendar/embed?src=retrium.com_2mt3sq805a20m9ucutlvqevba8%40group.calendar.google.com&ctz=America%2FNew_York

I imported the ICS, but subscribing is better so that as events are added or changed, I can see those changes. 

## Current Behavior
Feature would be added at https://www.agileventures.org/events

## Possible Solution

Add a link to a new page that provides the link and instructions on how to add the public calendar to your link (click on the + button).  The page could also describe what subscribing does.

This link tells you how to create a public calendar link for Google.
https://calendar.google.com/calendar/embed?src=hanoulle.be_vhhuilrdov5hiodkhauquvp7eg%40group.calendar.google.com

Below is a link to join a public calendar for Agile events.  On the bottom right, you can click on the + symbol to subscribe.  
https://calendar.google.com/calendar/embed?src=hanoulle.be_vhhuilrdov5hiodkhauquvp7eg%40group.calendar.google.com

Here is a link to the slack thread where it was suggested:
https://app.slack.com/client/T0285CSTT/C0285CSUF/thread/C02AA0ARR-1587583592.031100

**Comment by mattlindsey** [comment] 2020-11-04 12:08
Note that you can currently subscribe to the AgileVentures calendar, although it takes a few steps.
See also note on https://github.com/AgileVentures/WebsiteOne/issues/3590

**Comment by mattlindsey** [comment] 2020-11-06 21:15
Closing.  Duplicate of #3590

**Closed** 2021-06-01 21:23 UTC
